### PR TITLE
use cdnjs to load font-awesome

### PR DESCRIPTION
**Pull request by PeterDaveHello**
To speed up the website and make the structure much easier to be maintained.

### CODE REVIEW

**Comment by thomaspark** [comment]
Hi @PeterDaveHello, thanks for the pull request. But it doesn't seem like there's a major increase in speed (except possibly on first load if it's already been cached). The maintenance is also not a problem since I'm using npm for many other dependencies anyway.

**Comment by PeterDaveHello** [comment]
hm ... I think the speed to download from cloudflare is faster then download it directly from GitHub, and the assets don't need to be managed by git :smile:

**Comment by thomaspark** [comment]
According to my tests, the speed is basically identical. You might get different results if you're in Asia, but I think it will still be a pretty negligible difference.

**Comment by PeterDaveHello** [comment]
Okay, feel free to close :smile:

**Pull request closed without merging**
